# Generated by Django 4.2.8 on 2024-08-21 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_referencepoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referencepoint',
            old_name='latitude',
            new_name='easting',
        ),
        migrations.RenameField(
            model_name='referencepoint',
            old_name='longitude',
            new_name='northing',
        ),
    ]
